gems: [jekyll-paginate]
# Dependencies
markdown:            redcarpet

# Permalinks
permalink:           pretty

# Setup
title:               Kyle's Place
tagline:             'somewhere to put my thoughts'
description:         >
                     Posts I found helpful, tutorials I make, and somewhere to write when I'm bored
url:                 http://kyle.gorak.us
baseurl:             ''
paginate:            3

# Pages
pages:
  Archive: '/archive'
  About: '/about'
  Tags: '/tags'

# About/contact
author:
  name:              'Kyle Gorak'
  url:               http://kyle.gorak.us

github:
  repo:              https://github.com/gorhack/gorhack.github.io

sass:
  sass_dir: _sass
  style: :compressed

# Theme
theme:
 str_continue_reading: "Continue reading..."

# Custom vars
version:             1.0.0
twitter_username: g0rak
github_username:  gorhack
linkedin_shorturl: kylegorak
